#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

command_name=$(basename "$0")

function usage_exit() {
    cat << EOF >&2
Usage: $command_name unique-identifier [version]
EOF
    exit $1
}

if [ $# -ne 1 -a $# -ne 2 ]; then
    usage_exit 2
fi

if [ $# -eq 1 ]; then
    version=latest
else
    version="$2"
fi

parts=(${1//./ })

if [ ${#parts[@]} -ne 2 ]; then
    usage_exit 2
fi

wget -O "${parts[0]}.${parts[1]}-${version}.vsix" "https://${parts[0]}.gallery.vsassets.io/_apis/public/gallery/publisher/${parts[0]}/extension/${parts[1]}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"
