#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

command_name=$(basename "$0")

function usage_exit() {
    cat << EOF >&2
Usage: $command_name commit-id
EOF
    exit $1
}

if [ $# -ne 1 ]; then
    usage_exit 2
fi

wget -O vscode-server-linux-x64.tar.gz "https://update.code.visualstudio.com/commit:$1/server-linux-x64/stable"
