#+STARTUP: showall indent

* VSCode Utilities

Visual Studio Code（VSCode）のためのユティリティコマンド群です。

** ■ get-vsix

VSCode の拡張機能ファイル vsix をダウンロードするコマンドです。
VSCode をオフライン環境で利用する場合のために作成しました。
Linux で動作するシェルスクリプトと Windows で動作するバッチファイルがあります。

*** 使用方法

#+BEGIN_EXAMPLE
get-vsix unique-identifier [version]
#+END_EXAMPLE

version を省略すると、latest が指定されたものとなります。

*** 使用例

Japanese Language Pack for VS Code 拡張機能の vsix ファイルをダウンロードするには、
次のとおりのコマンドを入力することとなります。

#+BEGIN_EXAMPLE
get-vsix MS-CEINTL.vscode-language-pack-ja
get-vsix MS-CEINTL.vscode-language-pack-ja latest
get-vsix MS-CEINTL.vscode-language-pack-ja 1.99.2025032609
get-vsix MS-CEINTL.vscode-language-pack-ja 1.98.2025031209
#+END_EXAMPLE

unique-identifier、version の情報は、以下の Marketplace のサイトの右側 More Info の箇所で
確認できます。バージョン履歴は、Version History タブで確認することができます。

- https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-ja

ダウンロードされた vsix ファイルは、オフライン環境の PC に転送し、 VSCode アプリから
インストールしてください。

*** 活用例１

インターネットに接続している Windows PC 上の VSCode から オフライン環境にある VSCode に
全ての拡張機能を移行するには、次の方法で対応することができます。

**** 1) VSCode の拡張機能を vsix ファイルとしてダウンロードする

インターネットに接続している Windows PC で、次のコマンドを実行してください。

＜Windows 環境（コマンドプロンプト）で実行する場合＞
#+BEGIN_EXAMPLE
code --update-extensions

for /f "usebackq delims=" %i in (`code --list-extensions --show-versions`) do (
    for /f "tokens=1,2 delims=@" %a in ("%i") do (
        get-vsix %a %b
    )
)
#+END_EXAMPLE
※ バッチファイルにする場合は、先頭行に @echo off を追加し、全ての % を %% に置き換えて
ください。

＜WSL 環境（shell）で実行する場合＞
#+BEGIN_EXAMPLE
cmd.exe /c code --update-extensions

for i in $(cmd.exe /c code --list-extensions --show-versions 2> /dev/null); do
    parts=(${i//@/ })
    get-vsix ${parts[0]} ${parts[1]}
done
#+END_EXAMPLE

**** 2) ダウンロードした vsix ファイルを取り込む

オフライン環境にある Windows PC に 1) でダウンロードした vsix ファイルを複写し、VSCode
を終了させた後、次のコマンドを実行してください。

＜Windows 環境（コマンドプロンプト）で実行する場合＞
#+BEGIN_EXAMPLE
for %i in (*.vsix) do (
    code --install-extension %i
)
#+END_EXAMPLE
※ バッチファイルにする場合は、先頭行に @echo off を追加し、全ての % を %% に置き換えて
ください。

＜WSL 環境（shell）で実行する場合＞
#+BEGIN_EXAMPLE
for i in *.vsix; do
    cmd.exe /c code --install-extension $i
done
#+END_EXAMPLE
※ WSL 環境で実行する場合でも、vsix ファイルは Windows ファイルシステム配下に置く必要が
あります。（cmd.exe コマンドを利用しているため。）

*** 活用例２

オフライン環境にある Windows PC 上の VSCode の全ての拡張機能を最新バージョンするには、
次の方法で対応することができます。

拡張機能を最新バージョンする場合は、予め VSCode のバージョンも最新バージョンにして
ください。

なお、この活用例の場合、活用例１の場合とは異なり、VSCode のバージョンと拡張機能の
バージョンとで不整合が発生し、拡張機能がインストールできない場合があります。
その場合は、拡張機能のバージョンを指定してダウンロードするなど、個別に対応する必要が
あります。

**** 1) VSCode の拡張機能の unique-identifier のリストを取り込む

オフライン環境にある Windows PC のコマンドプロンプトで、次のコマンドを実行してください。

#+BEGIN_EXAMPLE
code --list-extensions > list.txt
#+END_EXAMPLE

**** 2) VSCode の拡張機能を vsix ファイルとしてダウンロードする

インターネットに接続している Windows PC に 1) で作成した list.txt を取り込み、
次のコマンドを実行してください。

＜Windows 環境（コマンドプロンプト）で実行する場合＞
#+BEGIN_EXAMPLE
for /F %i in (list.txt) do (
    get-vsix %i
)
#+END_EXAMPLE
※ バッチファイルにする場合は、先頭行に @echo off を追加し、全ての % を %% に置き換えて
ください。

＜WSL 環境（shell）で実行する場合＞
#+BEGIN_EXAMPLE
for i in $(cat list.txt); do
    get-vsix $i
done
#+END_EXAMPLE

**** 3) 必要に応じて、取り込んだ vsix ファイルをバージョンが分かるファイル名に変更する

＜Windows 環境（コマンドプロンプト）で実行する場合＞
#+BEGIN_EXAMPLE
for %i in (*-latest.vsix) do (
    python rename-vsix %i
)
#+END_EXAMPLE
※ バッチファイルにする場合は、先頭行に @echo off を追加し、全ての % を %% に置き換えて
ください。

＜WSL 環境（shell）で実行する場合＞
#+BEGIN_EXAMPLE
for i in *-latest.vsix; do
    rename-vsix $i
done
#+END_EXAMPLE

**** 4) ダウンロードした vsix ファイルを取り込む

オフライン環境にある Windows PC に 2) でダウンロードした vsix ファイルを複写し、
VSCode を終了させた後、次のコマンドを実行してください。

＜Windows 環境（コマンドプロンプト）で実行する場合＞
#+BEGIN_EXAMPLE
for %i in (*.vsix) do (
    code --install-extension %i
)
#+END_EXAMPLE
※ バッチファイルにする場合は、先頭行に @echo off を追加し、全ての % を %% に置き換えて
ください。

＜WSL 環境（shell）で実行する場合＞
#+BEGIN_EXAMPLE
for i in *.vsix; do
    cmd.exe /c code --install-extension $i
done
#+END_EXAMPLE
※ WSL 環境で実行する場合でも、vsix ファイルは Windows ファイルシステム配下に置く必要が
あります。（cmd.exe コマンドを利用しているため。）

*** 参考情報

- https://www.reddit.com/r/vscode/comments/1i6k7gf/cant_download_vsix_extensions_from_the_web/
- https://stackoverflow.com/questions/69398500/vscode-download-older-version-of-an-extension
- https://zenn.dev/yhatt/scraps/876f6fe83c901d

*** 拡張機能ファイルダウンロードサイト

- https://www.vsixhub.com/
- https://open-vsx.org/

** ■ get-vscode-server

VSCode の vscode-server ファイルをダウンロードするコマンドです。
VSCode をオフライン環境で利用する場合のために作成しました。
Linux で動作するシェルスクリプトと Windows で動作するバッチファイルがあります。

*** 使用方法

#+BEGIN_EXAMPLE
get-vscode-server commit-id
#+END_EXAMPLE

*** 使用例

#+BEGIN_EXAMPLE
get-vscode-server ddc367ed5c8936efe395cffeec279b04ffd7db78
#+END_EXAMPLE

commit-id の確認方法は、次のページを参照してください。

- https://www.mathkuro.com/vs-code/remote-development-in-offline/

コマンドを実行すると vscode-server-linux-x64.tar.gz という名称のファイルがダウンロードされます。
このファイルを VSCode のサーバとするマシンに転送し、次のコマンドを実行して展開してください。

#+BEGIN_EXAMPLE
cp vscode-server-linux-x64.tar.gz ~/.vscode-server/bin
cd ~/.vscode-server/bin
tar zxvf vscode-server-linux-x64.tar.gz
mv vscode-server-linux-x64 <commit-id>
rm vscode-server-linux-x64.tar.gz
#+END_EXAMPLE

<commit-id> の箇所は、vscode-server ファイルをダウンロードするときに指定した commit-id に
置き換えてください。上記の使用例の場合には、ddc367ed5c8936efe395cffeec279b04ffd7db78 となります。

*** 参考情報

- https://www.mathkuro.com/vs-code/remote-development-in-offline/
