#+STARTUP: showall indent

* VSCode Utilities

Visual Studio Code（VSCode）のためのユティリティコマンド群です。

Linux で動作します。コマンド内部で wget コマンドを利用しています。

** ■ get-vsix

VSCode の拡張機能ファイル vsix をダウンロードするコマンドです。
VSCode をオフライン環境で利用する場合のために作成しました。

*** 使用方法

#+BEGIN_EXAMPLE
get-vsix unique-identifier [version]
#+END_EXAMPLE

version を省略すると、latest が指定されたものとなります。

*** 使用例

Japanese Language Pack for VS Code 拡張機能の vsix ファイルをダウンロードするには、
次のとおりのコマンドを入力することとなります。

#+BEGIN_EXAMPLE
get-vsix MS-CEINTL.vscode-language-pack-ja
get-vsix MS-CEINTL.vscode-language-pack-ja latest
get-vsix MS-CEINTL.vscode-language-pack-ja 1.99.2025032609
get-vsix MS-CEINTL.vscode-language-pack-ja 1.98.2025031209
#+END_EXAMPLE

unique-identifier、version の情報は、以下の Marketplace のサイトの右側 More Info の箇所で
確認できます。バージョン履歴は、Version History タブで確認することができます。

- https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-ja

ダウンロードされた vsix ファイルは、オフライン環境の PC に転送し、 VSCode アプリから
インストールしてください。

*** 活用例

インターネットに接続している Windows PC 上の VSCode から オフライン環境にある VSCode に
全ての拡張機能を移行するには、次の方法で対応することができます。

**** 1) VSCode の拡張機能を vsix ファイルとしてダウンロードする

インターネットに接続している Windows PC の WSL の環境で次のコマンドを実行してください。

#+BEGIN_EXAMPLE
cmd.exe /c code --update-extensions

for i in $(cmd.exe /c code --list-extensions --show-versions 2> /dev/null);
do
    arr=(${i//@/ })
    get-vsix ${arr[0]} ${arr[1]}
done
#+END_EXAMPLE

**** 2) ダウンロードした vsix ファイルを取り込む

オフライン環境にある Windows PC の Windows ファイルシステム配下に 1) でダウンロードした
vsix フィアルを複写し、VSCode を終了させた後、次のコマンドを実行してください。

＜WSL 環境（shell）で実行する場合＞
#+BEGIN_EXAMPLE
for i in *.vsix
do
    cmd.exe /c code --install-extension $i
done
#+END_EXAMPLE

＜Windows 環境（コマンドプロンプト）で実行する場合＞
#+BEGIN_EXAMPLE
for %%i in (*.vsix) do (
    code --install-extension %%i
)
#+END_EXAMPLE

*** 参考情報

- https://www.reddit.com/r/vscode/comments/1i6k7gf/cant_download_vsix_extensions_from_the_web/

** ■ get-vscode-server

VSCode の vscode-server ファイルをダウンロードするコマンドです。
VSCode をオフライン環境で利用する場合のために作成しました。

*** 使用方法

#+BEGIN_EXAMPLE
get-vscode-server commit-id
#+END_EXAMPLE

*** 使用例

#+BEGIN_EXAMPLE
get-vscode-server ddc367ed5c8936efe395cffeec279b04ffd7db78
#+END_EXAMPLE

commit-id の確認方法は、次のページを参照してください。

- https://www.mathkuro.com/vs-code/remote-development-in-offline/

コマンドを実行すると vscode-server-linux-x64.tar.gz という名称のファイルがダウンロードされます。
このファイルを VSCode のサーバとするマシンに転送し、次のコマンドを実行して展開してください。

#+BEGIN_EXAMPLE
cp vscode-server-linux-x64.tar.gz ~/.vscode-server/bin
cd ~/.vscode-server/bin
tar zxvf vscode-server-linux-x64.tar.gz
mv vscode-server-linux-x64 <commit-id>
rm vscode-server-linux-x64.tar.gz
#+END_EXAMPLE

<commit-id> の箇所は、上記の使用例の場合には、ddc367ed5c8936efe395cffeec279b04ffd7db78
に置き換えてください。

*** 参考情報

- https://www.mathkuro.com/vs-code/remote-development-in-offline/
