#+STARTUP: showall indent

* VSCode Utilities

Visual Studio Code（VSCode）のためのユティリティコマンド群です。

Linux で動作します。コマンド内部で wget コマンドを利用しています。

** ■ get-vsix

VSCode の拡張機能ファイル vsix をダウンロードするコマンドです。
VSCode をオフライン環境で利用する場合のために作成しました。

*** 使用方法

#+BEGIN_EXAMPLE
get-vsix unique-identifier [version]
#+END_EXAMPLE

version を省略すると、latest が指定されたものとなります。

*** 使用例

Japanese Language Pack for VS Code 拡張機能の vsix ファイルをダウンロードするには、
次のとおりのコマンドを入力することとなります。

#+BEGIN_EXAMPLE
get-vsix MS-CEINTL.vscode-language-pack-ja
get-vsix MS-CEINTL.vscode-language-pack-ja latest
get-vsix MS-CEINTL.vscode-language-pack-ja 1.99.2025032609
get-vsix MS-CEINTL.vscode-language-pack-ja 1.98.2025031209
#+END_EXAMPLE

unique-identifier、version の情報は、以下の Marketplace のサイトの右側 More Info の箇所で
確認できます。バージョン履歴は、Version History タブで確認することができます。

- https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-ja

ダウンロードされた vsix ファイルは、オフライン環境の PC に転送し、 VSCode アプリから
インストールしてください。

*** 活用例

Windows で動作している VSCode の拡張機能を全て vsix ファイルとしてダウンロードするには、
WSL の環境上で次のコマンドを実行してください。

#+BEGIN_EXAMPLE
code --update-extensions

for i in $(cmd.exe /c code.cmd --list-extensions --show-versions 2> /dev/null);
do
    arr=(${i//@/ })
    get-vsix ${arr[0]} ${arr[1]}
done
#+END_EXAMPLE

ダウンロードした vsix ファイルを VSCode に一括で取り込むには、WSL の環境上で次のコマンドを
実行してください。vsix ファイルは Windows のファイルシステムエリアに置く必要があります。

#+BEGIN_EXAMPLE
for i in *.vsix
do
    cmd.exe /c code.cmd --install-extension $i
done
#+END_EXAMPLE

オフラインで動作する VSCode の環境構築のために利用できる手法と思われます。

*** 参考情報

- https://www.reddit.com/r/vscode/comments/1i6k7gf/cant_download_vsix_extensions_from_the_web/

** ■ get-vscode-server

VSCode の vscode-server ファイルをダウンロードするコマンドです。
VSCode をオフライン環境で利用する場合のために作成しました。

*** 使用方法

#+BEGIN_EXAMPLE
get-vscode-server commit-id
#+END_EXAMPLE

*** 使用例

#+BEGIN_EXAMPLE
get-vscode-server ddc367ed5c8936efe395cffeec279b04ffd7db78
#+END_EXAMPLE

commit-id の確認方法は、次のページを参照してください。

- https://www.mathkuro.com/vs-code/remote-development-in-offline/

コマンドを実行すると vscode-server-linux-x64.tar.gz という名称のファイルがダウンロードされます。
このファイルを VSCode のサーバとするマシンに転送し、次のコマンドを実行して展開してください。

#+BEGIN_EXAMPLE
cp vscode-server-linux-x64.tar.gz ~/.vscode-server/bin
cd ~/.vscode-server/bin
tar zxvf vscode-server-linux-x64.tar.gz
mv vscode-server-linux-x64 <commit-id>
rm vscode-server-linux-x64.tar.gz
#+END_EXAMPLE

<commit-id> の箇所は、上記の使用例の場合には、ddc367ed5c8936efe395cffeec279b04ffd7db78
に置き換えてください。

*** 参考情報

- https://www.mathkuro.com/vs-code/remote-development-in-offline/
